import { WeatherData } from './types';

export const CITIES_DATA: { [key: string]: WeatherData } = {
  'Hà Nội': {
    city: 'Hà Nội',
    country: 'Việt Nam',
    temp: 29,
    feelsLike: 32,
    humidity: 78,
    windSpeed: 14,
    uvIndex: 8,
    airQuality: 'Trung bình',
    airQualityDesc: 'Chất lượng không khí ở mức chấp nhận được. Người nhạy cảm nên hạn chế hoạt động mạnh ngoài trời.',
    airQualityCode: 72,
    pressure: 1012,
    condition: 'cloudy',
    description: 'Nhiều mây, trời dịu mát về chiều tối, có gió nhẹ',
    aiAdvice: 'Hôm nay Hà Nội có mây che phủ tốt, độ ẩm khá cao. Bạn nên chọn trang phục cotton mát mẻ, thấm hút mồ hôi. Buổi chiều tối có thể có mưa rào nhẹ, mang theo một chiếc ô nhỏ sẽ rất lý tưởng.',
    hourly: [
      { time: '06:00', temp: 26, icon: 'cloudy', rainProb: 15, humidity: 82 },
      { time: '09:00', temp: 28, icon: 'cloudy', rainProb: 20, humidity: 79 },
      { time: '12:00', temp: 31, icon: 'sunny', rainProb: 10, humidity: 70 },
      { time: '15:00', temp: 30, icon: 'cloudy', rainProb: 35, humidity: 74 },
      { time: '18:00', temp: 28, icon: 'rainy', rainProb: 60, humidity: 80 },
      { time: '21:00', temp: 27, icon: 'cloudy', rainProb: 40, humidity: 85 },
      { time: '00:00', temp: 26, icon: 'cloudy', rainProb: 20, humidity: 88 },
    ],
    daily: [
      { day: 'Hôm nay', date: '21 Th6', tempMin: 25, tempMax: 32, condition: 'cloudy', icon: 'cloudy', rainProb: 45, humidity: 78, uvIndex: 8 },
      { day: 'Thứ Hai', date: '22 Th6', tempMin: 26, tempMax: 34, condition: 'sunny', icon: 'sunny', rainProb: 10, humidity: 70, uvIndex: 10 },
      { day: 'Thứ Ba', date: '23 Th6', tempMin: 25, tempMax: 33, condition: 'stormy', icon: 'stormy', rainProb: 75, humidity: 85, uvIndex: 5 },
      { day: 'Thứ Tư', date: '24 Th6', tempMin: 24, tempMax: 30, condition: 'rainy', icon: 'rainy', rainProb: 90, humidity: 90, uvIndex: 3 },
      { day: 'Thứ Năm', date: '25 Th6', tempMin: 25, tempMax: 31, condition: 'cloudy', icon: 'cloudy', rainProb: 30, humidity: 80, uvIndex: 7 },
      { day: 'Thứ Sáu', date: '26 Th6', tempMin: 26, tempMax: 33, condition: 'sunny', icon: 'sunny', rainProb: 15, humidity: 72, uvIndex: 9 },
      { day: 'Thứ Bảy', date: '27 Th6', tempMin: 26, tempMax: 34, condition: 'sunny', icon: 'sunny', rainProb: 20, humidity: 75, uvIndex: 10 },
    ],
  },
  'TP. Hồ Chí Minh': {
    city: 'TP. Hồ Chí Minh',
    country: 'Việt Nam',
    temp: 32,
    feelsLike: 38,
    humidity: 82,
    windSpeed: 18,
    uvIndex: 11,
    airQuality: 'Tốt',
    airQualityDesc: 'Chất lượng không khí tuyệt vời, rất thích hợp cho các hoạt động thể thao ngoài trời.',
    airQualityCode: 35,
    pressure: 1008,
    condition: 'rainy',
    description: 'Nắng nóng ngắt quãng, chiều tối có mưa rào nhiệt đới kéo dài',
    aiAdvice: 'Thời tiết Sài Gòn nắng gắt ban ngày với UV cực kỳ cao (11+). Bạn PHẢI bôi kem chống nắng và đeo kính râm khi ra ngoài trước 16h. Đừng quên mang áo mưa vì cơn giông chiều tối có thể ập đến bất ngờ!',
    hourly: [
      { time: '06:00', temp: 27, icon: 'sunny', rainProb: 5, humidity: 88 },
      { time: '09:00', temp: 31, icon: 'sunny', rainProb: 10, humidity: 78 },
      { time: '12:00', temp: 33, icon: 'sunny', rainProb: 25, humidity: 65 },
      { time: '15:00', temp: 31, icon: 'rainy', rainProb: 70, humidity: 75 },
      { time: '18:00', temp: 28, icon: 'stormy', rainProb: 85, humidity: 88 },
      { time: '21:00', temp: 26, icon: 'rainy', rainProb: 50, humidity: 92 },
      { time: '00:00', temp: 25, icon: 'cloudy', rainProb: 30, humidity: 95 },
    ],
    daily: [
      { day: 'Hôm nay', date: '21 Th6', tempMin: 25, tempMax: 33, condition: 'rainy', icon: 'rainy', rainProb: 85, humidity: 82, uvIndex: 11 },
      { day: 'Thứ Hai', date: '22 Th6', tempMin: 26, tempMax: 34, condition: 'stormy', icon: 'stormy', rainProb: 80, humidity: 84, uvIndex: 9 },
      { day: 'Thứ Ba', date: '23 Th6', tempMin: 25, tempMax: 32, condition: 'rainy', icon: 'rainy', rainProb: 70, humidity: 86, uvIndex: 8 },
      { day: 'Thứ Tư', date: '24 Th6', tempMin: 25, tempMax: 33, condition: 'cloudy', icon: 'cloudy', rainProb: 40, humidity: 80, uvIndex: 10 },
      { day: 'Thứ Năm', date: '25 Th6', tempMin: 24, tempMax: 32, condition: 'rainy', icon: 'rainy', rainProb: 75, humidity: 85, uvIndex: 7 },
      { day: 'Thứ Sáu', date: '26 Th6', tempMin: 25, tempMax: 33, condition: 'sunny', icon: 'sunny', rainProb: 20, humidity: 76, uvIndex: 11 },
      { day: 'Thứ Bảy', date: '27 Th6', tempMin: 25, tempMax: 34, condition: 'sunny', icon: 'sunny', rainProb: 30, humidity: 74, uvIndex: 11 },
    ],
  },
  'Đồng Nai': {
    city: 'Đồng Nai',
    country: 'Việt Nam',
    temp: 31,
    feelsLike: 36,
    humidity: 80,
    windSpeed: 15,
    uvIndex: 10,
    airQuality: 'Tốt',
    airQualityDesc: 'Chất lượng không khí sạch, nhiều mảng cây xanh điều hoà tốt.',
    airQualityCode: 40,
    pressure: 1009,
    condition: 'cloudy',
    description: 'Nắng ấm nhẹ xen kẽ mây dông rải rác về trưa chiều',
    aiAdvice: 'Thời tiết Đồng Nai hôm nay khá oi bức, tia UV ở mức cao. Bạn nên chú ý mang theo vật dụng che nắng chuyên dụng, uống đủ nước khoáng ấm, và chuẩn bị sẵn áo mưa đề phòng các vệt dông nhiệt rải rác từ khu vực Long Khánh, Biên Hòa kéo tới.',
    hourly: [
      { time: '06:00', temp: 26, icon: 'sunny', rainProb: 5, humidity: 85 },
      { time: '09:00', temp: 29, icon: 'sunny', rainProb: 15, humidity: 76 },
      { time: '12:00', temp: 32, icon: 'cloudy', rainProb: 30, humidity: 68 },
      { time: '15:00', temp: 31, icon: 'rainy', rainProb: 65, humidity: 72 },
      { time: '18:00', temp: 28, icon: 'stormy', rainProb: 80, humidity: 82 },
      { time: '21:00', temp: 27, icon: 'rainy', rainProb: 40, humidity: 88 },
      { time: '00:00', temp: 25, icon: 'cloudy', rainProb: 20, humidity: 91 },
    ],
    daily: [
      { day: 'Hôm nay', date: '21 Th6', tempMin: 25, tempMax: 32, condition: 'cloudy', icon: 'cloudy', rainProb: 65, humidity: 80, uvIndex: 10 },
      { day: 'Thứ Hai', date: '22 Th6', tempMin: 26, tempMax: 33, condition: 'rainy', icon: 'rainy', rainProb: 80, humidity: 82, uvIndex: 9 },
      { day: 'Thứ Ba', date: '23 Th6', tempMin: 25, tempMax: 32, condition: 'stormy', icon: 'stormy', rainProb: 75, humidity: 85, uvIndex: 8 },
      { day: 'Thứ Tư', date: '24 Th6', tempMin: 24, tempMax: 31, condition: 'rainy', icon: 'rainy', rainProb: 70, humidity: 88, uvIndex: 7 },
      { day: 'Thứ Năm', date: '25 Th6', tempMin: 25, tempMax: 32, condition: 'cloudy', icon: 'cloudy', rainProb: 45, humidity: 78, uvIndex: 10 },
      { day: 'Thứ Sáu', date: '26 Th6', tempMin: 26, tempMax: 34, condition: 'sunny', icon: 'sunny', rainProb: 20, humidity: 72, uvIndex: 11 },
      { day: 'Thứ Bảy', date: '27 Th6', tempMin: 25, tempMax: 33, condition: 'sunny', icon: 'sunny', rainProb: 30, humidity: 74, uvIndex: 11 },
    ],
  },
  'Đà Nẵng': {
    city: 'Đà Nẵng',
    country: 'Việt Nam',
    temp: 31,
    feelsLike: 35,
    humidity: 70,
    windSpeed: 21,
    uvIndex: 9,
    airQuality: 'Tốt',
    airQualityDesc: 'Chất lượng không khí sạch, gió biển mát mẻ trong lành.',
    airQualityCode: 28,
    pressure: 1010,
    condition: 'windy',
    description: 'Trời nắng đẹp, nhiều gió, cực kỳ thoáng đãng',
    aiAdvice: 'Thời tiết Đà Nẵng hôm nay lý tưởng để tắm biển Mỹ Khê! Gió biển thổi khá mạnh nên cảm giác rất dễ chịu dù nắng. Bạn nên mặc áo mỏng nhẹ, đội mũ rộng vành và tranh thủ dạo phố vào ban đêm.',
    hourly: [
      { time: '06:00', temp: 27, icon: 'sunny', rainProb: 0, humidity: 75 },
      { time: '09:00', temp: 30, icon: 'sunny', rainProb: 5, humidity: 68 },
      { time: '12:00', temp: 32, icon: 'sunny', rainProb: 10, humidity: 62 },
      { time: '15:00', temp: 31, icon: 'windy', rainProb: 15, humidity: 65 },
      { time: '18:00', temp: 29, icon: 'windy', rainProb: 10, humidity: 72 },
      { time: '21:00', temp: 28, icon: 'sunny', rainProb: 5, humidity: 78 },
      { time: '00:00', temp: 27, icon: 'sunny', rainProb: 0, humidity: 80 },
    ],
    daily: [
      { day: 'Hôm nay', date: '21 Th6', tempMin: 26, tempMax: 32, condition: 'windy', icon: 'windy', rainProb: 15, humidity: 70, uvIndex: 9 },
      { day: 'Thứ Hai', date: '22 Th6', tempMin: 26, tempMax: 33, condition: 'sunny', icon: 'sunny', rainProb: 5, humidity: 68, uvIndex: 10 },
      { day: 'Thứ Ba', date: '23 Th6', tempMin: 27, tempMax: 34, condition: 'sunny', icon: 'sunny', rainProb: 10, humidity: 65, uvIndex: 10 },
      { day: 'Thứ Tư', date: '24 Th6', tempMin: 25, tempMax: 31, condition: 'cloudy', icon: 'cloudy', rainProb: 30, humidity: 75, uvIndex: 8 },
      { day: 'Thứ Năm', date: '25 Th6', tempMin: 24, tempMax: 30, condition: 'rainy', icon: 'rainy', rainProb: 65, humidity: 82, uvIndex: 6 },
      { day: 'Thứ Sáu', date: '26 Th6', tempMin: 25, tempMax: 32, condition: 'cloudy', icon: 'cloudy', rainProb: 20, humidity: 74, uvIndex: 8 },
      { day: 'Thứ Bảy', date: '27 Th6', tempMin: 26, tempMax: 33, condition: 'sunny', icon: 'sunny', rainProb: 10, humidity: 70, uvIndex: 11 },
    ],
  },
  'Sa Pa': {
    city: 'Sa Pa',
    country: 'Việt Nam',
    temp: 14,
    feelsLike: 12,
    humidity: 90,
    windSpeed: 8,
    uvIndex: 3,
    airQuality: 'Tuyệt vời',
    airQualityDesc: 'Không khí vùng núi cao trong lành tuyệt đối, mát mẻ cả ngày.',
    airQualityCode: 15,
    pressure: 1018,
    condition: 'snowy',
    description: 'Sương mù dày đặc bồng bềnh, băng tuyết nhẹ trên đỉnh Fansipan',
    aiAdvice: 'Sa Pa đang cực kỳ lạnh và ẩm ướt! Bạn cần chuẩn bị áo phao dày, găng tay và giày bít mũi chống trượt. Hãy thưởng thức một nồi lẩu cá hồi hay ấm trà gừng nóng hổi để sưởi ấm trong chiều sương.',
    hourly: [
      { time: '06:00', temp: 12, icon: 'snowy', rainProb: 40, humidity: 95 },
      { time: '09:00', temp: 13, icon: 'cloudy', rainProb: 30, humidity: 92 },
      { time: '12:00', temp: 15, icon: 'cloudy', rainProb: 25, humidity: 88 },
      { time: '15:00', temp: 16, icon: 'cloudy', rainProb: 30, humidity: 86 },
      { time: '18:00', temp: 14, icon: 'snowy', rainProb: 45, humidity: 92 },
      { time: '21:00', temp: 12, icon: 'snowy', rainProb: 50, humidity: 96 },
      { time: '00:00', temp: 10, icon: 'snowy', rainProb: 60, humidity: 98 },
    ],
    daily: [
      { day: 'Hôm nay', date: '21 Th6', tempMin: 10, tempMax: 16, condition: 'snowy', icon: 'snowy', rainProb: 60, humidity: 90, uvIndex: 3 },
      { day: 'Thứ Hai', date: '22 Th6', tempMin: 11, tempMax: 18, condition: 'cloudy', icon: 'cloudy', rainProb: 35, humidity: 85, uvIndex: 6 },
      { day: 'Thứ Ba', date: '23 Th6', tempMin: 13, tempMax: 20, condition: 'sunny', icon: 'sunny', rainProb: 15, humidity: 75, uvIndex: 8 },
      { day: 'Thứ Tư', date: '24 Th6', tempMin: 12, tempMax: 17, condition: 'rainy', icon: 'rainy', rainProb: 70, humidity: 92, uvIndex: 4 },
      { day: 'Thứ Năm', date: '25 Th6', tempMin: 10, tempMax: 15, condition: 'snowy', icon: 'snowy', rainProb: 50, humidity: 96, uvIndex: 2 },
      { day: 'Thứ Sáu', date: '26 Th6', tempMin: 11, tempMax: 17, condition: 'cloudy', icon: 'cloudy', rainProb: 30, humidity: 88, uvIndex: 5 },
      { day: 'Thứ Bảy', date: '27 Th6', tempMin: 12, tempMax: 19, condition: 'sunny', icon: 'sunny', rainProb: 10, humidity: 78, uvIndex: 8 },
    ],
  },
  'Nha Trang': {
    city: 'Nha Trang',
    country: 'Việt Nam',
    temp: 30,
    feelsLike: 33,
    humidity: 72,
    windSpeed: 16,
    uvIndex: 10,
    airQuality: 'Tốt',
    airQualityDesc: 'Không khí ven biển rất dịu nhẹ, lộng gió.',
    airQualityCode: 22,
    pressure: 1011,
    condition: 'sunny',
    description: 'Trời trong xanh, nắng trải vàng óng ả trên những bãi cát mịn',
    aiAdvice: 'Thời tiết Nha Trang hoàn hảo vô cùng! Thích hợp tối đa để đi du thuyền tham quan rạn san hô Hòn Mun, lướt ván và tắm nắng. Nhớ thoa kem chống nắng chỉ số SPF 50+ để làn da được bảo vệ toàn diện nhé.',
    hourly: [
      { time: '06:00', temp: 26, icon: 'sunny', rainProb: 0, humidity: 82 },
      { time: '09:00', temp: 29, icon: 'sunny', rainProb: 0, humidity: 74 },
      { time: '12:00', temp: 31, icon: 'sunny', rainProb: 5, humidity: 68 },
      { time: '15:00', temp: 30, icon: 'sunny', rainProb: 5, humidity: 70 },
      { time: '18:00', temp: 28, icon: 'sunny', rainProb: 0, humidity: 76 },
      { time: '21:00', temp: 27, icon: 'sunny', rainProb: 0, humidity: 80 },
      { time: '00:00', temp: 26, icon: 'sunny', rainProb: 0, humidity: 82 },
    ],
    daily: [
      { day: 'Hôm nay', date: '21 Th6', tempMin: 25, tempMax: 31, condition: 'sunny', icon: 'sunny', rainProb: 5, humidity: 72, uvIndex: 10 },
      { day: 'Thứ Hai', date: '22 Th6', tempMin: 26, tempMax: 32, condition: 'sunny', icon: 'sunny', rainProb: 5, humidity: 70, uvIndex: 10 },
      { day: 'Thứ Ba', date: '23 Th6', tempMin: 26, tempMax: 32, condition: 'sunny', icon: 'sunny', rainProb: 10, humidity: 71, uvIndex: 10 },
      { day: 'Thứ Tư', date: '24 Th6', tempMin: 25, tempMax: 31, condition: 'cloudy', icon: 'cloudy', rainProb: 20, humidity: 75, uvIndex: 8 },
      { day: 'Thứ Năm', date: '25 Th6', tempMin: 24, tempMax: 31, condition: 'rainy', icon: 'rainy', rainProb: 40, humidity: 78, uvIndex: 8 },
      { day: 'Thứ Sáu', date: '26 Th6', tempMin: 25, tempMax: 32, condition: 'sunny', icon: 'sunny', rainProb: 10, humidity: 73, uvIndex: 10 },
      { day: 'Thứ Bảy', date: '27 Th6', tempMin: 26, tempMax: 33, condition: 'sunny', icon: 'sunny', rainProb: 5, humidity: 69, uvIndex: 11 },
    ],
  },
  'Tokyo': {
    city: 'Tokyo',
    country: 'Nhật Bản',
    temp: 22,
    feelsLike: 22,
    humidity: 55,
    windSpeed: 10,
    uvIndex: 6,
    airQuality: 'Tốt',
    airQualityDesc: 'Chất lượng cuộc sống chuẩn xanh, không khí sạch tốt lành.',
    airQualityCode: 24,
    pressure: 1016,
    condition: 'cloudy',
    description: 'Trời râm mát mát, nhiều gió thoảng hương hoa cúc họa mi',
    aiAdvice: 'Thời tiết Tokyo đang bước vào mùa dễ chịu nhất. Trưa ấm nhẹ, tối mát mẻ se lạnh. Hãy rảo bước ở Shibuya hay công viên Ueno với một chiếc áo khoác Cardigan mỏng bọc ngoài trang phục thường nhật.',
    hourly: [
      { time: '06:00', temp: 18, icon: 'cloudy', rainProb: 5, humidity: 68 },
      { time: '09:00', temp: 21, icon: 'sunny', rainProb: 10, humidity: 60 },
      { time: '12:00', temp: 23, icon: 'sunny', rainProb: 15, humidity: 52 },
      { time: '15:00', temp: 22, icon: 'cloudy', rainProb: 20, humidity: 55 },
      { time: '18:00', temp: 20, icon: 'cloudy', rainProb: 15, humidity: 62 },
      { time: '21:00', temp: 19, icon: 'cloudy', rainProb: 10, humidity: 66 },
      { time: '00:00', temp: 18, icon: 'cloudy', rainProb: 5, humidity: 70 },
    ],
    daily: [
      { day: 'Hôm nay', date: '21 Th6', tempMin: 18, tempMax: 23, condition: 'cloudy', icon: 'cloudy', rainProb: 20, humidity: 55, uvIndex: 6 },
      { day: 'Thứ Hai', date: '22 Th6', tempMin: 17, tempMax: 24, condition: 'sunny', icon: 'sunny', rainProb: 5, humidity: 50, uvIndex: 8 },
      { day: 'Thứ Ba', date: '23 Th6', tempMin: 18, tempMax: 22, condition: 'rainy', icon: 'rainy', rainProb: 80, humidity: 78, uvIndex: 3 },
      { day: 'Thứ Tư', date: '24 Th6', tempMin: 16, tempMax: 21, condition: 'stormy', icon: 'stormy', rainProb: 90, humidity: 82, uvIndex: 2 },
      { day: 'Thứ Năm', date: '25 Th6', tempMin: 17, tempMax: 23, condition: 'cloudy', icon: 'cloudy', rainProb: 15, humidity: 60, uvIndex: 7 },
      { day: 'Thứ Sáu', date: '26 Th6', tempMin: 18, tempMax: 25, condition: 'sunny', icon: 'sunny', rainProb: 5, humidity: 54, uvIndex: 9 },
      { day: 'Thứ Bảy', date: '27 Th6', tempMin: 19, tempMax: 26, condition: 'sunny', icon: 'sunny', rainProb: 10, humidity: 58, uvIndex: 9 },
    ],
  },
  'Paris': {
    city: 'Paris',
    country: 'Pháp',
    temp: 18,
    feelsLike: 17,
    humidity: 62,
    windSpeed: 23,
    uvIndex: 4,
    airQuality: 'Tốt',
    airQualityDesc: 'Thời tiết sạch bừng sáng sau cơn mưa nhẹ rạng đông.',
    airQualityCode: 42,
    pressure: 1013,
    condition: 'rainy',
    description: 'Có mưa bụi lãng mạn lướt qua tháp Eiffel rồi tạnh ráo',
    aiAdvice: 'Cơn mưa phùn Paris lướt nhanh nhưng kéo theo những đợt gió lạnh từ sông Seine. Một chiếc măng-tô sành điệu kèm chiếc khăn voan hay ô cầm tay sẽ biến bạn đúng chuẩn một người Paris thời thượng.',
    hourly: [
      { time: '06:00', temp: 15, icon: 'rainy', rainProb: 80, humidity: 88 },
      { time: '09:00', temp: 16, icon: 'rainy', rainProb: 65, humidity: 82 },
      { time: '12:00', temp: 18, icon: 'cloudy', rainProb: 40, humidity: 68 },
      { time: '15:00', temp: 19, icon: 'sunny', rainProb: 30, humidity: 58 },
      { time: '18:00', temp: 18, icon: 'cloudy', rainProb: 20, humidity: 60 },
      { time: '21:00', temp: 16, icon: 'cloudy', rainProb: 10, humidity: 66 },
      { time: '00:00', temp: 14, icon: 'cloudy', rainProb: 5, humidity: 72 },
    ],
    daily: [
      { day: 'Hôm nay', date: '21 Th6', tempMin: 14, tempMax: 19, condition: 'rainy', icon: 'rainy', rainProb: 80, humidity: 62, uvIndex: 4 },
      { day: 'Thứ Hai', date: '22 Th6', tempMin: 13, tempMax: 20, condition: 'cloudy', icon: 'cloudy', rainProb: 30, humidity: 65, uvIndex: 6 },
      { day: 'Thứ Ba', date: '23 Th6', tempMin: 14, tempMax: 22, condition: 'sunny', icon: 'sunny', rainProb: 10, humidity: 58, uvIndex: 7 },
      { day: 'Thứ Tư', date: '24 Th6', tempMin: 15, tempMax: 23, condition: 'sunny', icon: 'sunny', rainProb: 15, humidity: 54, uvIndex: 8 },
      { day: 'Thứ Năm', date: '25 Th6', tempMin: 15, tempMax: 21, condition: 'rainy', icon: 'rainy', rainProb: 60, humidity: 74, uvIndex: 5 },
      { day: 'Thứ Sáu', date: '26 Th6', tempMin: 13, tempMax: 20, condition: 'stormy', icon: 'stormy', rainProb: 85, humidity: 80, uvIndex: 3 },
      { day: 'Thứ Bảy', date: '27 Th6', tempMin: 14, tempMax: 22, condition: 'cloudy', icon: 'cloudy', rainProb: 20, humidity: 68, uvIndex: 7 },
    ],
  },
};

export const PRESET_CITIES = Object.keys(CITIES_DATA);
